import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BreakpointOverlay from "./components/utils/BreakpointOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="lg:px-10 px-4 lg:h-screen w-screen overflow-hidden">
          {children}
        </div>
        <BreakpointOverlay />
      </body>
    </html>
  );
}
