import { Geist, Geist_Mono, Manrope } from "next/font/google"; // ⬅️ Manrope importieren
import "./globals.css";
import BreakpointOverlay from "./components/utils/BreakpointOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({ 
  variable: "--font-manrope", 
  subsets: ["latin"], 
}); // ⬅️ Manrope richtig laden

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Setzen der pinken Farbe für die Browser-Oberfläche
  themeColor: "#ff007f", // Pinke Farbe
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Meta Tag für Browserfarbe */}
        <meta name="theme-color" content="#ff00ff" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`} // ⬅️ Manrope einfügen
      >
        <div className="lg:h-screen w-screen overflow-hidden">
          {children}
        </div>
        {/* <BreakpointOverlay /> */}
      </body>
    </html>
  );
}
